// Centralized list of all tools for the homepage and navigation
export const tools = [
  { name: "ASCII to Base64", slug: "ascii-to-base64", description: "Convert ASCII text to Base64 encoding." },
  { name: "ASCII to Base64 (Alt)", slug: "ascii-to-base64-alt", description: "Alternative ASCII to Base64 converter." },
  { name: "ASCII to Text", slug: "ascii-to-text", description: "Convert ASCII codes to text." },
  { name: "Audio to Base64", slug: "audio-to-base64", description: "Convert audio files to Base64." },
  { name: "Base64 Encode", slug: "base64-encode", description: "Encode text or files to Base64." },
  { name: "Base64 to ASCII", slug: "base64-to-ascii", description: "Decode Base64 to ASCII text." },
  { name: "Base64 to ASCII (Alt)", slug: "base64-to-ascii-alt", description: "Alternative Base64 to ASCII converter." },
  { name: "Base64 to Binary", slug: "base64-to-binary", description: "Decode Base64 to binary." },
  { name: "Base64 to CSS", slug: "base64-to-css", description: "Decode Base64 to CSS code." },
  { name: "Base64 to CSV", slug: "base64-to-csv", description: "Decode Base64 to CSV." },
  { name: "Base64 to Hexadecimal", slug: "base64-to-hexadecimal", description: "Decode Base64 to hexadecimal values." },
  { name: "Base64 to HTML", slug: "base64-to-html", description: "Decode Base64 to HTML code." },
  { name: "Base64 to Image", slug: "base64-to-image", description: "Decode Base64 to images." },
  { name: "Base64 to JavaScript", slug: "base64-to-javascript", description: "Decode Base64 to JavaScript code." },
  { name: "Base64 to JSON", slug: "base64-to-json", description: "Decode Base64 to JSON." },
  { name: "Base64 to Octal", slug: "base64-to-octal", description: "Decode Base64 to octal values." },
  { name: "Base64 to Text", slug: "base64-to-text", description: "Decode Base64 to plain text." },
  { name: "Base64 to TSV", slug: "base64-to-tsv", description: "Decode Base64 to TSV." },
  { name: "Base64 to XML", slug: "base64-to-xml", description: "Decode Base64 to XML." },
  { name: "Base64 to YAML", slug: "base64-to-yaml", description: "Decode Base64 to YAML." },
  { name: "Binary to Base64", slug: "binary-to-base64", description: "Convert binary to Base64." },
  { name: "BMP to Base64", slug: "bmp-to-base64", description: "Convert BMP images to Base64." },
  { name: "Byte to ASCII", slug: "byte-to-ascii", description: "Convert bytes to ASCII characters." },
  { name: "Char to ASCII", slug: "char-to-ascii", description: "Get ASCII value of a character." },
  { name: "Color Converter", slug: "color-converter", description: "Convert between HEX, RGB, HSV, and more." },
  { name: "CSS to Base64", slug: "css-to-base64", description: "Encode CSS code to Base64." },
  { name: "CSV to Base64", slug: "csv-to-base64", description: "Encode CSV to Base64." },
  { name: "Decimal to ASCII", slug: "decimal-to-ascii", description: "Convert decimal to ASCII character." },
  { name: "GIF to Base64", slug: "gif-to-base64", description: "Convert GIF images to Base64." },
  { name: "Hexadecimal to Base64", slug: "hexadecimal-to-base64", description: "Encode hexadecimal values to Base64." },
  { name: "HTML to Base64", slug: "html-to-base64", description: "Encode HTML code to Base64." },
  { name: "Image to ASCII Art", slug: "image-to-ascii-art", description: "Transform images into ASCII art." },
  { name: "Image to Base64", slug: "image-to-base64", description: "Convert images to Base64." },
  { name: "JavaScript to Base64", slug: "javascript-to-base64", description: "Encode JavaScript code to Base64." },
  { name: "JPEG to Base64", slug: "jpeg-to-base64", description: "Convert JPEG images to Base64." },
  { name: "JSON Beautifier", slug: "json-beautifier", description: "Format and beautify your JSON data." },
  { name: "JSON to Base64", slug: "json-to-base64", description: "Encode JSON to Base64." },
  { name: "AI Tools", slug: "ai-tools", description: "Online AI Tools." },
  { name: "Base64 Decode", slug: "base64-decode", description: "Online Base64 Decode Tool." },
  { name: "Binary to Text", slug: "binary-to-text", description: "Online Binary to Text Tool." },
  { name: "Checksum Calculator", slug: "checksum-calculator", description: "Online Checksum Calculator Tool." },
  { name: "CMYK to Hex", slug: "cmyk-to-hex", description: "Online CMYK to Hex Tool." },
  { name: "CMYK to HSV", slug: "cmyk-to-hsv", description: "Online CMYK to HSV Tool." },
  { name: "CMYK to Pantone", slug: "cmyk-to-pantone", description: "Online CMYK to Pantone Tool." },
  { name: "CMYK to RGB", slug: "cmyk-to-rgb", description: "Online CMYK to RGB Tool." },
  { name: "Color Desaturation", slug: "color-desaturation", description: "Online Color Desaturation Tool." },
  { name: "CRC 16 Hash Generator", slug: "crc-16-hash-generator", description: "Online CRC 16 Hash Generator Tool." },
  { name: "CRC 32 Hash Generator", slug: "crc-32-hash-generator", description: "Online CRC 32 Hash Generator Tool." },
  { name: "CSS Background Color Generator", slug: "css-background-color-generator", description: "Online CSS Background Color Generator Tool." },
  { name: "CSS Background Image Generator", slug: "css-background-image-generator", description: "Online CSS Background Image Generator Tool." },
  { name: "CSS Beautifier", slug: "css-beautifier", description: "Online CSS Beautifier Tool." },
  { name: "CSS Border Generator", slug: "css-border-generator", description: "Online CSS Border Generator Tool." },
  { name: "CSS Border Radius Generator", slug: "css-border-radius-generator", description: "Online CSS Border Radius Generator Tool." },
  { name: "CSS Box Resize Generator", slug: "css-box-resize-generator", description: "Online CSS Box Resize Generator Tool." },
  { name: "CSS Box Shadow Generator", slug: "css-box-shadow-generator", description: "Online CSS Box Shadow Generator Tool." },
  { name: "CSS Minify", slug: "css-minify", description: "Online CSS Minify Tool." },
  { name: "CSS to LESS", slug: "css-to-less", description: "Online CSS to LESS Tool." },
  { name: "CSS to SCSS", slug: "css-to-scss", description: "Online CSS to SCSS Tool." },
  { name: "CSS to Stylus", slug: "css-to-stylus", description: "Online CSS to Stylus Tool." },
  { name: "Encryption Decryption", slug: "encryption-decryption", description: "Online Encryption Decryption Tool." },
  { name: "GIF to Base64", slug: "gif-to-base64", description: "Online GIF to Base64 Tool." },
  { name: "GZIP Decompress Online", slug: "gzip-decompress-online", description: "Online GZIP Decompress Tool." },
  { name: "Hex to CMYK", slug: "hex-to-cmyk", description: "Online Hex to CMYK Tool." },
  { name: "Hex to HSV", slug: "hex-to-hsv", description: "Online Hex to HSV Tool." },
  { name: "Hex to Pantone", slug: "hex-to-pantone", description: "Online Hex to Pantone Tool." },
  { name: "Hex to RGB", slug: "hex-to-rgb", description: "Online Hex to RGB Tool." },
  { name: "Hex to RGBA", slug: "hex-to-rgba", description: "Online Hex to RGBA Tool." },
  { name: "Hex to String", slug: "hex-to-string", description: "Online Hex to String Tool." },
  { name: "HTML Decode", slug: "html-decode", description: "Online HTML Decode Tool." },
  { name: "HTML Encode", slug: "html-encode", description: "Online HTML Encode Tool." },
  { name: "HTML Escape", slug: "html-escape", description: "Online HTML Escape Tool." },
  { name: "HTML Escape Unescape", slug: "html-escape-unescape", description: "Online HTML Escape Unescape Tool." },
  { name: "HTML Formatter", slug: "html-formatter", description: "Online HTML Formatter Tool." },
  { name: "HTML Minify", slug: "html-minify", description: "Online HTML Minify Tool." },
  { name: "HTML to Base64", slug: "html-to-base64", description: "Online HTML to Base64 Tool." },
  { name: "HTML Unescape", slug: "html-unescape", description: "Online HTML Unescape Tool." },
  { name: "Invert Colors", slug: "invert-colors", description: "Online Invert Colors Tool." },
  { name: "JavaScript to Base64 Alt", slug: "javascript-to-base64-alt", description: "Online JavaScript to Base64 Alt Tool." },
  { name: "JSON Cleaner", slug: "json-cleaner", description: "Online JSON Cleaner Tool." },
  { name: "JSON Diff", slug: "json-diff", description: "Online JSON Diff Tool." },
  { name: "JSON Editor", slug: "json-editor", description: "Online JSON Editor Tool." },
  { name: "JSON Escape Unescape", slug: "json-escape-unescape", description: "Online JSON Escape Unescape Tool." },
  { name: "JSON Minifier", slug: "json-minifier", description: "Online JSON Minifier Tool." },
  { name: "JSON Minify", slug: "json-minify", description: "Online JSON Minify Tool." },
  { name: "JSON Parser Online", slug: "json-parser-online", description: "Online JSON Parser Tool." },
  { name: "JSON Path Tester", slug: "json-path-tester", description: "Online JSON Path Tester Tool." },
  { name: "JSON Sorter", slug: "json-sorter", description: "Online JSON Sorter Tool." },
  { name: "JSON to C Sharp", slug: "json-to-c-sharp", description: "Online JSON to C# Tool." },
  { name: "JSON to CSV", slug: "json-to-csv", description: "Online JSON to CSV Tool." },
  { name: "JSON to HTML", slug: "json-to-html", description: "Online JSON to HTML Tool." },
  { name: "JSON to JavaScript", slug: "json-to-javascript", description: "Online JSON to JavaScript Tool." },
  { name: "JSON to PHP Array", slug: "json-to-php-array", description: "Online JSON to PHP Array Tool." },
  { name: "JSON to Python", slug: "json-to-python", description: "Online JSON to Python Tool." },
  { name: "JSON to Text Converter", slug: "json-to-text-converter", description: "Online JSON to Text Converter Tool." },
  { name: "JSON to XML", slug: "json-to-xml", description: "Online JSON to XML Tool." },
  { name: "JSON to YAML", slug: "json-to-yaml", description: "Online JSON to YAML Tool." },
  { name: "JSON Unminify", slug: "json-unminify", description: "Online JSON Unminify Tool." },
  { name: "JSON URL Decode", slug: "json-url-decode", description: "Online JSON URL Decode Tool." },
  { name: "JSON URL Encode", slug: "json-url-encode", description: "Online JSON URL Encode Tool." },
  { name: "JSON Validator", slug: "json-validator", description: "Online JSON Validator Tool." },
  { name: "JSON Viewer", slug: "json-viewer", description: "Online JSON Viewer Tool." },
  { name: "JWT Decode", slug: "jwt-decode", description: "Online JWT Decode Tool." },
  { name: "Less Beautifier", slug: "less-beautifier", description: "Online Less Beautifier Tool." },
  { name: "MD2 Hash Generator", slug: "md2-hash-generator", description: "Online MD2 Hash Generator Tool." },
  { name: "MD4 Hash Generator", slug: "md4-hash-generator", description: "Online MD4 Hash Generator Tool." },
  { name: "MD5 Hash Generator", slug: "md5-hash-generator", description: "Online MD5 Hash Generator Tool." },
  { name: "MD6 Hash Generator", slug: "md6-hash-generator", description: "Online MD6 Hash Generator Tool." },
  { name: "MP3 to Base64", slug: "mp3-to-base64", description: "Online MP3 to Base64 Tool." },
  { name: "NTLM Hash Generator", slug: "ntlm-hash-generator", description: "Online NTLM Hash Generator Tool." },
  { name: "Octal to Base64", slug: "octal-to-base64", description: "Online Octal to Base64 Tool." },
  { name: "Pantone to CMYK", slug: "pantone-to-cmyk", description: "Online Pantone to CMYK Tool." },
  { name: "Pantone to Hex", slug: "pantone-to-hex", description: "Online Pantone to Hex Tool." },
  { name: "Pantone to HSV", slug: "pantone-to-hsv", description: "Online Pantone to HSV Tool." },
  { name: "Pantone to RGB", slug: "pantone-to-rgb", description: "Online Pantone to RGB Tool." },
  { name: "Password Generator", slug: "password-generator", description: "Online Password Generator Tool." },
  { name: "PNG to Base64", slug: "png-to-base64", description: "Online PNG to Base64 Tool." },
  { name: "Random JSON Generator", slug: "random-json-generator", description: "Online Random JSON Generator Tool." },
  { name: "Random Number Generator", slug: "random-number-generator", description: "Online Random Number Generator Tool." },
  { name: "RGB to CMYK", slug: "rgb-to-cmyk", description: "Online RGB to CMYK Tool." },
  { name: "RGB to Hex", slug: "rgb-to-hex", description: "Online RGB to Hex Tool." },
  { name: "RGB to HSV", slug: "rgb-to-hsv", description: "Online RGB to HSV Tool." },
  { name: "RGB to Pantone", slug: "rgb-to-pantone", description: "Online RGB to Pantone Tool." },
  { name: "SCSS Beautifier", slug: "scss-beautifier", description: "Online SCSS Beautifier Tool." },
  { name: "SHA1 Hash Generator", slug: "sha1-hash-generator", description: "Online SHA1 Hash Generator Tool." },
  { name: "SHA2 Hash Generator", slug: "sha2-hash-generator", description: "Online SHA2 Hash Generator Tool." },
  { name: "SHA224 Hash Generator", slug: "sha224-hash-generator", description: "Online SHA224 Hash Generator Tool." },
  { name: "SHA256 Hash Generator", slug: "sha256-hash-generator", description: "Online SHA256 Hash Generator Tool." },
  { name: "SHA3 224 Hash Generator", slug: "sha3-224-hash-generator", description: "Online SHA3 224 Hash Generator Tool." },
  { name: "SHA3 256 Hash Generator", slug: "sha3-256-hash-generator", description: "Online SHA3 256 Hash Generator Tool." },
  { name: "SHA3 384 Hash Generator", slug: "sha3-384-hash-generator", description: "Online SHA3 384 Hash Generator Tool." },
  { name: "SHA3 512 Hash Generator", slug: "sha3-512-hash-generator", description: "Online SHA3 512 Hash Generator Tool." },
  { name: "SHA384 Hash Generator", slug: "sha384-hash-generator", description: "Online SHA384 Hash Generator Tool." },
  { name: "SHA512 224 Hash Gen", slug: "sha512-224-hash-gen", description: "Online SHA512 224 Hash Gen Tool." },
  { name: "SHA512 256 Hash Gen", slug: "sha512-256-hash-gen", description: "Online SHA512 256 Hash Gen Tool." },
  { name: "SHA512 Hash Generator", slug: "sha512-hash-generator", description: "Online SHA512 Hash Generator Tool." },
  { name: "Shake 128 Hash Generator", slug: "shake-128-hash-generator", description: "Online Shake 128 Hash Generator Tool." },
  { name: "Shake 256 Hash Generator", slug: "shake-256-hash-generator", description: "Online Shake 256 Hash Generator Tool." },
  { name: "String to Hex", slug: "string-to-hex", description: "Online String to Hex Tool." },
  { name: "Stylus Compiler", slug: "stylus-compiler", description: "Online Stylus Compiler Tool." },
  { name: "Stylus to CSS", slug: "stylus-to-css", description: "Online Stylus to CSS Tool." },
  { name: "Stylus to Less", slug: "stylus-to-less", description: "Online Stylus to Less Tool." },
  { name: "Stylus to Sass", slug: "stylus-to-sass", description: "Online Stylus to Sass Tool." },
  { name: "Stylus to SCSS", slug: "stylus-to-scss", description: "Online Stylus to SCSS Tool." },
  { name: "SVG to Base64", slug: "svg-to-base64", description: "Online SVG to Base64 Tool." },
  { name: "Text to ASCII", slug: "text-to-ascii", description: "Online Text to ASCII Tool." },
  { name: "Text to Base64", slug: "text-to-base64", description: "Online Text to Base64 Tool." },
  { name: "Text to Binary", slug: "text-to-binary", description: "Online Text to Binary Tool." },
  { name: "Tint and Shades Generator", slug: "tint-and-shades-generator", description: "Online Tint and Shades Generator Tool." },
  { name: "TSV to Base64", slug: "tsv-to-base64", description: "Online TSV to Base64 Tool." },
  { name: "Unix Timestamp Converter", slug: "unix-timestamp-converter", description: "Online Unix Timestamp Converter Tool." },
  { name: "URL Decode", slug: "url-decode", description: "Online URL Decode Tool." },
  { name: "URL Encode", slug: "url-encode", description: "Online URL Encode Tool." },
  { name: "URL Encoder Decoder", slug: "url-encoder-decoder", description: "Online URL Encoder Decoder Tool." },
  { name: "URL Parser", slug: "url-parser", description: "Online URL Parser Tool." },
  { name: "URL Unshortener", slug: "url-unshortener", description: "Online URL Unshortener Tool." },
  { name: "User Agent Parser", slug: "user-agent-parser", description: "Online User Agent Parser Tool." },
  { name: "UTF8 to ASCII", slug: "utf8-to-ascii", description: "Online UTF8 to ASCII Tool." },
  { name: "UUID Generator", slug: "uuid-generator", description: "Online UUID Generator Tool." },
  { name: "WebP to Base64", slug: "webp-to-base64", description: "Online WebP to Base64 Tool." },
  { name: "Whirlpool Hash Generator", slug: "whirlpool-hash-generator", description: "Online Whirlpool Hash Generator Tool." },
  { name: "Wordpress Password Hash", slug: "wordpress-password-hash", description: "Online Wordpress Password Hash Tool." },
  { name: "XML Escape Unescape", slug: "xml-escape-unescape", description: "Online XML Escape Unescape Tool." },
  { name: "XML Formatter", slug: "xml-formatter", description: "Online XML Formatter Tool." },
  { name: "XML Minify", slug: "xml-minify", description: "Online XML Minify Tool." },
  { name: "XML to Base64", slug: "xml-to-base64", description: "Online XML to Base64 Tool." },
  { name: "YAML Escape Unescape", slug: "yaml-escape-unescape", description: "Online YAML Escape Unescape Tool." },
  { name: "YAML Formatter", slug: "yaml-formatter", description: "Online YAML Formatter Tool." },
  { name: "YAML Minify", slug: "yaml-minify", description: "Online YAML Minify Tool." },
  { name: "YAML to Base64", slug: "yaml-to-base64", description: "Online YAML to Base64 Tool." },
  { name: "Zlib Decompress Online", slug: "zlib-decompress-online", description: "Online Zlib Decompress Tool." }
];
