import Link from "next/link";
import styles from "../styles/Tools.module.scss";

const tools = [
  { name: "AI Tools", slug: "ai-tools" },
  { name: "ASCII to Base64", slug: "ascii-to-base64" },
  { name: "ASCII to Base64 (Alt)", slug: "ascii-to-base64-alt" },
  { name: "ASCII to Text", slug: "ascii-to-text" },
  { name: "Audio to Base64", slug: "audio-to-base64" },
  { name: "Base64 Decode", slug: "base64-decode" },
  { name: "Base64 Encode", slug: "base64-encode" },
  { name: "Base64 to ASCII", slug: "base64-to-ascii" },
  { name: "Base64 to ASCII (Alt)", slug: "base64-to-ascii-alt" },
  { name: "Base64 to Binary", slug: "base64-to-binary" },
  { name: "Base64 to CSS", slug: "base64-to-css" },
  { name: "Base64 to CSV", slug: "base64-to-csv" },
  { name: "Base64 to Hexadecimal", slug: "base64-to-hexadecimal" },
  { name: "Base64 to HTML", slug: "base64-to-html" },
  { name: "Base64 to Image", slug: "base64-to-image" },
  { name: "Base64 to JavaScript", slug: "base64-to-javascript" },
  { name: "Base64 to JavaScript (Alt)", slug: "base64-to-javascript-alt" },
  { name: "Base64 to JSON", slug: "base64-to-json" },
  { name: "Base64 to Octal", slug: "base64-to-octal" },
  { name: "Base64 to Text", slug: "base64-to-text" },
  { name: "Base64 to TSV", slug: "base64-to-tsv" },
  { name: "Base64 to XML", slug: "base64-to-xml" },
  { name: "Base64 to YAML", slug: "base64-to-yaml" },
  { name: "Binary to Base64", slug: "binary-to-base64" },
  { name: "Binary to Text", slug: "binary-to-text" },
  { name: "BMP to Base64", slug: "bmp-to-base64" },
  { name: "Byte to ASCII", slug: "byte-to-ascii" },
  { name: "Char to ASCII", slug: "char-to-ascii" },
  { name: "Checksum Calculator", slug: "checksum-calculator" },
  { name: "CMYK to HEX", slug: "cmyk-to-hex" },
  { name: "CMYK to HSV", slug: "cmyk-to-hsv" },
  { name: "CMYK to Pantone", slug: "cmyk-to-pantone" },
  { name: "CMYK to RGB", slug: "cmyk-to-rgb" },
  { name: "Color Converter", slug: "color-converter" },
  { name: "Color Desaturation", slug: "color-desaturation" },
  { name: "CRC-16 Hash Generator", slug: "crc-16-hash-generator" },
  { name: "CRC-32 Hash Generator", slug: "crc-32-hash-generator" },
  { name: "CSS Background Color Generator", slug: "css-background-color-generator" },
  { name: "CSS Background Image Generator", slug: "css-background-image-generator" },
  { name: "CSS Beautifier", slug: "css-beautifier" },
  { name: "CSS Border Generator", slug: "css-border-generator" },
  { name: "CSS Border Radius Generator", slug: "css-border-radius-generator" },
  { name: "CSS Box Resize Generator", slug: "css-box-resize-generator" },
  { name: "CSS Box Shadow Generator", slug: "css-box-shadow-generator" },
  { name: "CSS Minify", slug: "css-minify" },
  { name: "CSS to Base64", slug: "css-to-base64" },
  { name: "CSS to LESS", slug: "css-to-less" },
  { name: "CSS to SCSS", slug: "css-to-scss" },
  { name: "CSS to Stylus", slug: "css-to-stylus" },
  { name: "CSS Validator", slug: "css-validator" },
  { name: "CSV to Base64", slug: "csv-to-base64" },
  { name: "Decimal to ASCII", slug: "decimal-to-ascii" },
  { name: "GIF to Base64", slug: "gif-to-base64" },
  { name: "Hexadecimal to Base64", slug: "hexadecimal-to-base64" },
  { name: "HTML Beautifier", slug: "html-beautifier" },
  { name: "HTML Decode", slug: "html-decode" },
  { name: "HTML Encode", slug: "html-encode" },
  { name: "HTML Escape/Unescape", slug: "html-escape-unescape" },
  { name: "HTML Formatter", slug: "html-formatter" },
  { name: "HTML Minify", slug: "html-minify" },
  { name: "HTML to Base64", slug: "html-to-base64" },
  { name: "Image to ASCII Art", slug: "image-to-ascii-art" },
  { name: "Image to Base64", slug: "image-to-base64" },
  { name: "Invert Colors", slug: "invert-colors" },
  { name: "JavaScript to Base64", slug: "javascript-to-base64" },
  { name: "JPEG to Base64", slug: "jpeg-to-base64" },
  { name: "JSON Beautifier", slug: "json-beautifier" },
  { name: "JSON Cleaner", slug: "json-cleaner" },
  { name: "JSON Formatter", slug: "json-formatter" },
  { name: "JSON Minify", slug: "json-minify" },
  { name: "JSON Parser Online", slug: "json-parser-online" },
  { name: "JSON Sorter", slug: "json-sorter" },
  { name: "JSON to Base64", slug: "json-to-base64" },
  { name: "JSON to C#", slug: "json-to-c-sharp" },
  { name: "JSON to CSV", slug: "json-to-csv" },
  { name: "JSON to HTML", slug: "json-to-html" },
  { name: "JSON to JavaScript", slug: "json-to-javascript" },
  { name: "JSON to PHP Array", slug: "json-to-php-array" },
  { name: "JSON to Python", slug: "json-to-python" },
  { name: "JSON to Text Converter", slug: "json-to-text-converter" },
  { name: "JSON to XML", slug: "json-to-xml" },
  { name: "JSON to YAML", slug: "json-to-yaml" },
  { name: "JSON URL Decode", slug: "json-url-decode" },
  { name: "JSON URL Encode", slug: "json-url-encode" },
  { name: "JSON Validator", slug: "json-validator" },
  { name: "LESS Beautifier", slug: "less-beautifier" },
  { name: "MD6 Hash Generator", slug: "md6-hash-generator" },
  { name: "MP3 to Base64", slug: "mp3-to-base64" },
  { name: "Octal to Base64", slug: "octal-to-base64" },
  { name: "Pantone to HSV", slug: "pantone-to-hsv" },
  { name: "Pantone to RGB", slug: "pantone-to-rgb" },
  { name: "PNG to Base64", slug: "png-to-base64" },
  { name: "Random JSON Generator", slug: "random-json-generator" },
  { name: "Random Number Generator", slug: "random-number-generator" },
  { name: "SCSS Beautifier", slug: "scss-beautifier" },
  { name: "SVG to Base64", slug: "svg-to-base64" },
  { name: "Stylus to CSS", slug: "stylus-to-css" },
  { name: "Stylus to LESS", slug: "stylus-to-less" },
  { name: "Text to ASCII", slug: "text-to-ascii" },
  { name: "Text to Base64", slug: "text-to-base64" },
  { name: "Text to Binary", slug: "text-to-binary" },
  { name: "TSV to Base64", slug: "tsv-to-base64" },
  { name: "URL Encoder/Decoder", slug: "url-encoder-decoder" },
  { name: "URL Parser", slug: "url-parser" },
  { name: "URL Unshortener", slug: "url-unshortener" },
  { name: "User Agent Parser", slug: "user-agent-parser" },
  { name: "UTF8 to ASCII", slug: "utf8-to-ascii" },
  { name: "UUID Generator", slug: "uuid-generator" },
  { name: "WebP to Base64", slug: "webp-to-base64" },
  { name: "XML Escape/Unescape", slug: "xml-escape-unescape" },
  { name: "XML Formatter", slug: "xml-formatter" },
  { name: "XML Minify", slug: "xml-minify" },
  { name: "XML to Base64", slug: "xml-to-base64" },
  { name: "YAML Beautifier", slug: "yaml-beautifier" },
  { name: "YAML Escape/Unescape", slug: "yaml-escape-unescape" },
  { name: "YAML Formatter", slug: "yaml-formatter" },
  { name: "YAML Minify", slug: "yaml-minify" },
  { name: "YAML to Base64", slug: "yaml-to-base64" }
];

export default function ToolsPage() {
  return (
    <main className={styles.tools}>
      <h1>All Tools</h1>
      <ul className={styles.toolList}>
        {tools.map((tool) => (
          <li key={tool.slug}>
            <Link href={`/tools/${tool.slug}`}>{tool.name}</Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
